name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout 
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}   
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/test-ci:${{github.sha}}
    -
      name: Update values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'deployment/deployment.yaml'
        propertyPath: 'spec.template.spec.containers[0].image'
        value: ${{ secrets.DOCKER_USERNAME }}/test-ci:${{github.sha}}
        createPR: true
        branch: main
        title: "Update"
        token: ${{secrets.TOKEN_GIT}}
