name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout 
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}   
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/test-ci:${{github.sha}}
    -
      name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        repository: Kevin-Moreau65/Infra-AKS-PFE
        path: other-repo
        token: ${{ secrets.TOKEN_GIT }} 
    -
      name: Update values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'test/deployment.yaml'
        propertyPath: 'spec.template.spec.containers[0].image'
        value: ${{ secrets.DOCKER_USERNAME }}/test-ci:${{github.sha}}
        commitChange: true
        branch: main
        repository: Kevin-Moreau65/infra-aks-pfe
        message: "Updated test"
        token: ${{secrets.TOKEN_GIT}}
        workDir: other-repo
